apiVersion: v1
kind: PersistentVolume
metadata:
  name: <name_pv>
  labels:
    app: <label>
spec:
  capacity:
    storage: <size>Gi
  # le champ volumeMode requiert l'activation de la "feature gate" Alpha BlockVolume
  volumeMode: Filesystem # Block
  accessModes:
  - ReadWriteOnce #ReadWriteMany - ReadOnlyMany
  persistentVolumeReclaimPolicy: Delete # Retain
  storageClassName: <storage_class_name>
  claimRef:
    namespace: <namespace_name_pvc>
    name: <pvc_name>
  local:
    path: /path/to/dir or /path/to/file
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - <hostnames>
