apiVersion: v1
kind: PersistentVolume
metadata:
  name: ssl
  labels:
    app: fibi
spec:
  capacity:
    storage: 1Gi
  # le champ volumeMode requiert l'activation de la "feature gate" Alpha BlockVolume
  volumeMode: Filesystem # Block
  accessModes:
  - ReadWriteOnce #ReadWriteMany - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain  # Delete 
  storageClassName: manual
  claimRef:
    namespace: test-dev
    name: ssl
  local:
    path: /etc/ssl/private # or /path/to/file
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - okd-cp-1.okd.osupytheas.fr
          - okd-cp-2.okd.osupytheas.fr
          - okd-cp-3.okd.osupytheas.fr
