kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ssl
  namespace: test-dev
spec:
  accessModes:
    - ReadWriteOnce # ReadWriteMany - ReadOnlyMany
  selector:
    matchLabels:
      app: test
  resources:
    requests:
      storage: 1Gi # Must be under or equal to the size of the pv
